on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 6 * * 6'
    
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        crystal: [1.0.0, latest, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
